const { join } = require('path');

module.exports = {
	defaultValues: {
		namespace: 'outermost',
		slug: 'dynamic-block',
		textdomain: 'dynamic-block',
		version: '0.1.0',
		pluginURI: 'https://www.nickdiego.com',
		author: 'Nick Diego',
		category: 'widgets',
		title: 'Dynamic Block',
		description: 'A dynamic block.',
		attributes: {},
		supports: {
			html: false,
		},
		// Customize the editor and style file names.
		editorStyle: 'file:./editor.css',
		style: 'file:./style.css',
		// Add the render file to use when rendering the block type on the server to show on the front end.
		render: 'file:./render.php',
		customPackageJSON: {
			prettier: '@wordpress/prettier-config',
		},
		customScripts: {
			'lint:js': 'wp-scripts lint-js ./src',
			'lint:js:fix': 'wp-scripts lint-js ./src --fix',
			'update-pot': 'wp i18n make-pot . languages/dynamic-block.pot --exclude=src',
		},
		// Needed to remove the empty `.js` files generated by webpack.
		npmDevDependencies: ['webpack-remove-empty-scripts'],
	},
	pluginTemplatesPath: join( __dirname, 'plugin' ),
	blockTemplatesPath: join( __dirname, 'src' ),
};